# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.4.2 dcfac5b"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "nft"
template_type = "Rust"

[[contracts]]
name = "token-logic-custom-quantity"
template_type = "CSharedLib"

[[contracts]]
name = "token-logic-approve"
template_type = "CSharedLib"

[[contracts]]
name = "token-logic-reject"
template_type = "CSharedLib"
